-- MySQL Script generated by MySQL Workbench
-- Sun May 31 13:55:43 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tic` DEFAULT CHARACTER SET utf8 ;
USE `tic` ;

-- -----------------------------------------------------
-- Table `tic`.`tipoactividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`tipoactividad` (
  `IdTipoActividad` INT(4) NOT NULL COMMENT 'Identifica el id del tipo de actividad',
  `TipDescripcion` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Describe el tipo de actividad',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`IdTipoActividad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tic`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`modulo` (
  `IdModulo` INT(3) NOT NULL AUTO_INCREMENT COMMENT 'Identifica el id modulo que se esta trabajando',
  `ModDescripcion` VARCHAR(300) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Identifica el nombre del modulo ',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`IdModulo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tic`.`actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`actividad` (
  `IdActividad` INT(3) NOT NULL COMMENT 'Identifica el numero de actividad',
  `ActDescripcion` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Descrpcion de la actividad',
  `ActFecha` DATE NOT NULL COMMENT 'Fecha de la actividad',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `TipoActividad_IdTipoActividad` INT(11) NOT NULL,
  `modulo_IdModulo` INT(3) NOT NULL,
  PRIMARY KEY (`IdActividad`, `TipoActividad_IdTipoActividad`, `modulo_IdModulo`),
  INDEX `fk_Actividad_TipoActividad1_idx` (`TipoActividad_IdTipoActividad` ASC),
  INDEX `fk_actividad_modulo1_idx` (`modulo_IdModulo` ASC),
  CONSTRAINT `fk_Actividad_TipoActividad1`
    FOREIGN KEY (`TipoActividad_IdTipoActividad`)
    REFERENCES `tic`.`tipoactividad` (`IdTipoActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_modulo1`
    FOREIGN KEY (`modulo_IdModulo`)
    REFERENCES `tic`.`modulo` (`IdModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tic`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`profesor` (
  `Idprofesor` INT(2) NOT NULL AUTO_INCREMENT COMMENT 'Id unica para un profesor',
  `ProNombre` VARCHAR(40) NOT NULL COMMENT 'Identifica el nombre del profesor',
  `ProApellido` VARCHAR(40) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Identifica el apellido de un profesor',
  `ProCorreo` VARCHAR(55) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Identifica el correo del profesor ',
  `ProDocumentoIdentidad` INT(12) NOT NULL COMMENT 'Identifica el numero de docuento de un profesor\\n',
  `ProCiudad` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Identifica la ciudad de un profesor ',
  `ProGenero` VARCHAR(45) NOT NULL COMMENT 'Identifica el genero de un profesor',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`Idprofesor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tic`.`AsignacionProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`AsignacionProfesor` (
  `idAsignacionProfesor` INT NOT NULL AUTO_INCREMENT,
  `modulo_IdModulo` INT(3) NOT NULL,
  `profesor_Idprofesor` INT(2) NOT NULL,
  PRIMARY KEY (`idAsignacionProfesor`, `modulo_IdModulo`, `profesor_Idprofesor`),
  INDEX `fk_AsignacionProfesor_modulo1_idx` (`modulo_IdModulo` ASC),
  INDEX `fk_AsignacionProfesor_profesor1_idx` (`profesor_Idprofesor` ASC),
  CONSTRAINT `fk_AsignacionProfesor_modulo1`
    FOREIGN KEY (`modulo_IdModulo`)
    REFERENCES `tic`.`modulo` (`IdModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AsignacionProfesor_profesor1`
    FOREIGN KEY (`profesor_Idprofesor`)
    REFERENCES `tic`.`profesor` (`Idprofesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tic`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`curso` (
  `IdCurso` INT(5) NOT NULL AUTO_INCREMENT COMMENT 'Id unico para un curso',
  `CurNum` INT(5) NOT NULL COMMENT 'Numero del curso',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `AsignacionProfesor_idAsignacionProfesor` INT NOT NULL,
  PRIMARY KEY (`IdCurso`, `AsignacionProfesor_idAsignacionProfesor`),
  INDEX `fk_curso_AsignacionProfesor1_idx` (`AsignacionProfesor_idAsignacionProfesor` ASC),
  CONSTRAINT `fk_curso_AsignacionProfesor1`
    FOREIGN KEY (`AsignacionProfesor_idAsignacionProfesor`)
    REFERENCES `tic`.`AsignacionProfesor` (`idAsignacionProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tic`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`estudiante` (
  `IdEstudiante` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Id unica para un estudiante',
  `EstNombre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Identifica el nombre de un estudiante',
  `EstApellido` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `EstCorreo` VARCHAR(55) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Identifica el correo de un estudiante',
  `EstDocumentoIdentidad` INT(12) NOT NULL COMMENT 'Identifica el numero de documento de un estudiante\\n',
  `EstCiudad` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Identifica la ciudad del estudiante',
  `EstGenero` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Identifica el genero de un estudiante\\n',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `curso_IdCurso` INT(5) NOT NULL,
  `modulo_IdModulo` INT(3) NOT NULL,
  PRIMARY KEY (`IdEstudiante`, `curso_IdCurso`, `modulo_IdModulo`),
  INDEX `fk_estudiante_curso1_idx` (`curso_IdCurso` ASC),
  INDEX `fk_estudiante_modulo1_idx` (`modulo_IdModulo` ASC),
  CONSTRAINT `fk_estudiante_curso1`
    FOREIGN KEY (`curso_IdCurso`)
    REFERENCES `tic`.`curso` (`IdCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_modulo1`
    FOREIGN KEY (`modulo_IdModulo`)
    REFERENCES `tic`.`modulo` (`IdModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tic`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`calificaciones` (
  `IdCalificacion` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Habra un Id de calificaciones',
  `CalNota` INT(3) NOT NULL COMMENT 'Esta sera la calificacion del usuario',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `actividad_IdActividad` INT(3) NOT NULL,
  `estudiante_IdEstudiante` INT(11) NOT NULL,
  PRIMARY KEY (`IdCalificacion`, `actividad_IdActividad`, `estudiante_IdEstudiante`),
  INDEX `fk_calificaciones_actividad1_idx` (`actividad_IdActividad` ASC),
  INDEX `fk_calificaciones_estudiante1_idx` (`estudiante_IdEstudiante` ASC),
  CONSTRAINT `fk_calificaciones_actividad1`
    FOREIGN KEY (`actividad_IdActividad`)
    REFERENCES `tic`.`actividad` (`IdActividad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaciones_estudiante1`
    FOREIGN KEY (`estudiante_IdEstudiante`)
    REFERENCES `tic`.`estudiante` (`IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tic`.`categorialibro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`categorialibro` (
  `catLibId` INT(11) NOT NULL AUTO_INCREMENT,
  `catLibNombre` VARCHAR(60) NOT NULL,
  `catLibEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `catLibObservacion` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`catLibId`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tic`.`libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`libros` (
  `isbn` INT(5) NOT NULL DEFAULT 0,
  `titulo` VARCHAR(236) NULL DEFAULT NULL,
  `autor` VARCHAR(305) NULL DEFAULT NULL,
  `precio` VARCHAR(10) NULL DEFAULT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `categoriaLibro_catLibId` INT(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`isbn`, `categoriaLibro_catLibId`),
  INDEX `fk_libros_categoriaLibro1_idx` (`categoriaLibro_catLibId` ASC),
  CONSTRAINT `fk_libros_categoriaLibro1`
    FOREIGN KEY (`categoriaLibro_catLibId`)
    REFERENCES `tic`.`categorialibro` (`catLibId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tic`.`usuario_s`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`usuario_s` (
  `usuId` INT(11) NOT NULL AUTO_INCREMENT,
  `usuLogin` VARCHAR(50) NOT NULL,
  `usuPassword` VARCHAR(100) NOT NULL,
  `usuUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `usuEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `usuRemember_token` VARCHAR(100) NOT NULL,
  `usu_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `usu_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`usuId`),
  UNIQUE INDEX `uniq_login` (`usuLogin` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tic`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`persona` (
  `perId` INT(11) NOT NULL COMMENT 'Nos muetsra el Id de la tabla persona',
  `perDocumento` VARCHAR(20) NOT NULL COMMENT 'Nos muestra el documento de la persona',
  `perNombre` VARCHAR(100) NOT NULL COMMENT 'Nos muestra el nombre de la persona',
  `perApellido` VARCHAR(255) NOT NULL COMMENT 'Nos muestra el apellido de la persona',
  `perEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `perUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `per_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `per_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `usuario_s_usuId` INT(11) NOT NULL,
  PRIMARY KEY (`perId`, `usuario_s_usuId`),
  UNIQUE INDEX `uniq_documento` (`perDocumento` ASC),
  INDEX `fk_persona_usuario_s1_idx` (`usuario_s_usuId` ASC),
  CONSTRAINT `fk_persona_usuario_s1`
    FOREIGN KEY (`usuario_s_usuId`)
    REFERENCES `tic`.`usuario_s` (`usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'Esta tabla nos muestra los datos de la persona ';


-- -----------------------------------------------------
-- Table `tic`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`rol` (
  `rolId` INT(11) NOT NULL AUTO_INCREMENT,
  `rolNombre` VARCHAR(32) NOT NULL,
  `rolDescripcion` VARCHAR(255) NOT NULL,
  `rolEstado` TINYINT(1) NOT NULL DEFAULT 1,
  `rolUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `rol_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `rol_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`rolId`),
  UNIQUE INDEX `uniq_nombrerol` (`rolNombre` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tic`.`usuario_s_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`usuario_s_roles` (
  `id_usuario_s` INT(11) NOT NULL,
  `id_rol` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT 1,
  `fechaUserRol` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `obsFechaUserRol` TEXT NULL DEFAULT NULL,
  `usuRolUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_usuario_s`, `id_rol`),
  INDEX `usuario_s_roles_fk_rolidrol` (`id_rol` ASC),
  CONSTRAINT `usuario_s_roles_fk_rolidrol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `tic`.`rol` (`rolId`),
  CONSTRAINT `usuario_s_roles_fk_usuario_sid`
    FOREIGN KEY (`id_usuario_s`)
    REFERENCES `tic`.`usuario_s` (`usuId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `tic`.`videoteca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tic`.`videoteca` (
  `IdVideo` INT(3) UNSIGNED NOT NULL COMMENT 'Describe el id de un video',
  `VidDescripcion` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'Describe el nombre de un video donde se sabe a que modulo pertenece',
  `Estado` TINYINT(1) NOT NULL DEFAULT 1,
  `Ususesion` VARCHAR(20) NULL DEFAULT NULL,
  `Created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `Update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `modulo_IdModulo` INT(3) NOT NULL,
  PRIMARY KEY (`IdVideo`, `modulo_IdModulo`),
  INDEX `fk_videoteca_modulo1_idx` (`modulo_IdModulo` ASC),
  CONSTRAINT `fk_videoteca_modulo1`
    FOREIGN KEY (`modulo_IdModulo`)
    REFERENCES `tic`.`modulo` (`IdModulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
